USE [master]
GO

/****** Object:  Database [flashcards]    Script Date: 1/19/2026 5:32:20 PM ******/
CREATE DATABASE [flashcards]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'flashcards', FILENAME = N'C:\Users\barak\flashcards.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'flashcards_log', FILENAME = N'C:\Users\barak\flashcards_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [flashcards].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [flashcards] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [flashcards] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [flashcards] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [flashcards] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [flashcards] SET ARITHABORT OFF 
GO

ALTER DATABASE [flashcards] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [flashcards] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [flashcards] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [flashcards] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [flashcards] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [flashcards] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [flashcards] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [flashcards] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [flashcards] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [flashcards] SET  DISABLE_BROKER 
GO

ALTER DATABASE [flashcards] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [flashcards] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [flashcards] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [flashcards] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [flashcards] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [flashcards] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [flashcards] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [flashcards] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [flashcards] SET  MULTI_USER 
GO

ALTER DATABASE [flashcards] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [flashcards] SET DB_CHAINING OFF 
GO

ALTER DATABASE [flashcards] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [flashcards] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [flashcards] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [flashcards] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [flashcards] SET QUERY_STORE = OFF
GO

ALTER DATABASE [flashcards] SET  READ_WRITE 
GO


