<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c1cdb04b-837e-4def-b81b-1f0da2b15c77</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <None Remove="Controllers\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Scripts\init_card_create.sql" />
    <None Remove="Scripts\init_create_db.sql" />
    <None Remove="Scripts\init_stack_create.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Scripts\init_card_create.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Scripts\init_create_db.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Scripts\init_stack_create.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.10" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="181.25.0" />
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

</Project>
